services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U administrator -d todo"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://administrator:verySecretPassword@database:5432/todo"
    ports:
      - "6400:6400"
    depends_on:
      database:
        condition: service_healthy
        restart: true
    
volumes:
  database-data: